const ACTION_TYPES = {
  /*
  * COMMON
  * CHECK_LOGIN_SUCCESS：登录成功
  * CHECK_LOGIN_FAILURE：登录失败
  * GET_USER_INFO:获取用户信息
  * GET_USER_INFO_SUCCESS: 获取用户信息成功
  * GET_USER_INFO_FAILURE:获取用户信息失败
  * */
  CHECK_LOGIN_FAILURE: 'CHECK_LOGIN_FAILURE',
  CHECK_LOGIN_SUCCESS: 'CHECK_LOGIN_SUCCESS',
  GET_USER_INFO: 'GET_USER_INFO',
  GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
  GET_USER_INFO_FAILURE: 'GET_USER_INFO_FAILURE',
  /*
  * 加载状态
  * COMMON
  * Loading开始
  * Loading结束
  * */
  LOADING_START: 'LOADING_START',
  LOADING_END: 'LOADING_END',

  /**
   * LOGIN 登录
   */
  LOGIN_REQUEST: 'LOGIN_REQUEST', // 登录接口
};

export default ACTION_TYPES;
